jobapp/urls.py
from django.urls import path
from .views import *


app_name = "jobapp"
urlpatterns = [
    path("", JobSeekerHomeView.as_view(), name="jobseekerhome"),
    path("employer/", EmployerHomeView.as_view(), name="employerhome"),
    path("job-admin/", AdminHomeView.as_view(), name="adminhome"),
    path("job/list/",
         JobListView.as_view(), name="joblist"),
    path("job/<int:pk>/detail/",
         JobDetailView.as_view(), name="jobdetail"),
    path("jobseeker/registration/", JobSeekerRegistrationView.as_view(),
         name="jobseekerregistration"),
    path("job/<int:pk>/apply/", JobSeekerJobApplyView.as_view(),
         name="jobseekerjobapply"),
    path("job/login/", JobLoginView.as_view(), name="joblogin"),
    path("jobseeker/profile", JobSeekerProfileView.as_view(),
         name="jobseekerprofile"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("employer/registration/", EmployerRegistrationView.as_view(),
         name="employerregistration"),
    path("employer/home/", EmployerHomeView.as_view(), name="employerhome"),
    path("employer/profile", EmployerProfileView.as_view(), name="employerprofile"),
    path("employer/job/<int:pk>/detail/",
         EmployerJobDetailView.as_view(), name="employerjobdetail"),
    path("employer/job/post/", EmployerJobCreateView.as_view(),
         name="employerjobcreate")
]

jobproject/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jobapp.urls')),
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/employertemplates/employerbase.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all" />
</head>
<body class="container">
	<nav class="nav">
		<li><a href="{% url 'jobapp:employerhome' %}">home</a></li>|
		<li><a href="{% url 'jobapp:employerjobcreate' %}">Post new Job</a></li>|

		{% if request.user.is_authenticated and request.user.groups.first.name == "employer" %}
      
        	<p>Logged in as : {{request.user}}</p>|
     		<li class="nav-item">
		      <a class="nav-link" href="{% url 'jobapp:employerprofile' %}">My Pofile</a>
		      </li>|


		      <li class="nav-item {% block logout %}{% endblock %}">
		        <a class="nav-link" href="{% url 'jobapp:logout' %}">logout</a>
		      </li>    
		      {% else %}
		      <li class="nav-item {% block registration %}{% endblock %}">
		        <a class="nav-link" href="{% url 'jobapp:employerregistration' %}">Register</a>
		      </li>|
		      <li class="nav-item {% block login %}{% endblock %}">
		        <a class="nav-link" href="{% url 'jobapp:joblogin' %}">login</a>
		      </li>
      	{% endif %}
		
	</nav>

{% block content %}



{% endblock %}


<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.0.min.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/employertemplates/employerhome.html
{% extends "employertemplates/employerbase.html" %}


{% block content %}

<h3>this is employer home</h3>

{% endblock %}

templates/employertemplates/employerjobcreate.html
{% extends "employertemplates/employerbase.html" %}



{% block content %}
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<button>Post</button>
</form>



{% endblock %}

templates/employertemplates/employerjobdetail.html
{% extends "employertemplates/employerbase.html" %}


{% block content %}
<h4>job title:{{jobobject.title}}</h4>
<h4>job Category:{{jobobject.category}}</h4>

<h3>job Application for this job</h3><hr>
<table class="table">
	<thead>
		<tr>
			<th>Sn</th>
			<th>applicants</th>
			<th>applied on</th>
			<th>download CV</th>
		</tr>
	</thead>
	<tbody>
		{% for application in jobobject.jobapplication_set.all %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td>{{application.jobseeker}}</td>
			<td>{{application.created_at}}</td>
			<td><a href="{{application.jobseeker.cv.url}}" download>Download CV</a>|
				<a href="{{application.cover_letter.url}}" download>Download Cover Letter</a></td>
		</tr>
		{% endfor %}
	</tbody>
</table>


{% endblock %}

templates/employertemplates/employerprofile.html
{% extends "employertemplates/employerbase.html" %}
{% load static %}

{% block content %}
<h3>Job Posted by: {{employer.company}}</h3>
<table class="table">
	<thead>
		<tr>
			<th>Sn.</th>
			<th>title</th>
			<th>Deadline</th>
			<th>Posted on</th>
		</tr>
	</thead>
	<tbody>
		{% for job in employer.job_set.all %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td><a href="{% url 'jobapp:employerjobdetail' job.id %}">{{job.title}}({{job.jobapplication_set.count}} applications)</a></td>
			<td>{{job.deadline}}</td>
			<td>{{job.created_at}}</td>
		</tr>
		{% endfor %}
	</tbody>	
</table>

{% endblock %}

templates/employertemplates/employerregistration.html
{% extends "employertemplates/employerbase.html" %}
{% load static %}

{% block content %}

<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<button>Register</button>
</form>


{% endblock %}