jobapp/urls.py
from django.urls import path
from .views import *


app_name = "jobapp"
urlpatterns = [
    path("", JobSeekerHomeView.as_view(), name="jobseekerhome"),
    path("employer/", EmployerHomeView.as_view(), name="employerhome"),
    path("job-admin/", AdminHomeView.as_view(), name="adminhome"),
    path("job/list/",
         JobListView.as_view(), name="joblist"),
    path("job/<int:pk>/detail/",
         JobDetailView.as_view(), name="jobdetail"),
    path("jobseeker/registration/", JobSeekerRegistrationView.as_view(),
         name="jobseekerregistration"),
    path("job/<int:pk>/apply/", JobSeekerJobApplyView.as_view(),
         name="jobseekerjobapply"),
    path("job/login/", JobLoginView.as_view(), name="joblogin"),
    path("jobseeker/profile", JobSeekerProfileView.as_view(),
         name="jobseekerprofile"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("employer/registration/", EmployerRegistrationView.as_view(),
         name="employerregistration"),
    path("employer/home/", EmployerHomeView.as_view(), name="employerhome"),
    path("employer/profile", EmployerProfileView.as_view(), name="employerprofile"),
    path("employer/job/<int:pk>/detail/",
         EmployerJobDetailView.as_view(), name="employerjobdetail"),
    path("employer/job/post/", EmployerJobCreateView.as_view(),
         name="employerjobcreate")
]

jobproject/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jobapp.urls')),
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/jobseekertemplates/jobdetail.html
{% extends "jobseekertemplates/jobseekerbase.html" %}
{% block job %}active{% endblock %}


{% block content %}
<div class="row">
	<div class="col-md-6">
		<u><h3>{{job.title}}</h3></u>
		<p style="color: orange">{{job.view_count}}</p>
		<img src="{{job.image.url}}" class="img-fluid">
	</div>
	<div class="col-md-6">
		<table class="table table-striped">
				<tr>
					<th>Job Title:</th>
					<td>{{job.title}}</td>
				</tr>
				<tr>
					<th>Required Skills:</th>
					<td>{{job.skills}}</td>
				</tr>
				<tr>
					<th>Education:</th>
					<td>{{job.education}}</td>
				</tr>
				<tr>
					<th>Job type:</th>
					<td>{{job.job_type}}</td>
				</tr>
				<tr>
					<th>employer:</th>
					<td>{{job.employer}}</td>
				</tr>
				<tr>
					<th>Salary:</th>
					<td>{{job.salary}}</td>
				</tr>
				<tr>
					<th>Level:</th>
					<td>{{job.level}}</td>
				</tr>
				<tr>
					<th>Vacancy:</th>
					<td>{{job.vacancy_number}}</td>
				</tr>
				<tr>
					<th>Detail:</th>
					<td>{{job.detail}}</td>
				</tr>
				<tr>
					<th>Deadline:</th>
					<td>{{job.deadline}}</td>
				</tr>

		</table>
	</div>
	
</div>

<a href="{% url 'jobapp:jobseekerjobapply' job.id %}">Apply Now</a>

{% endblock %}

templates/jobseekertemplates/joblist.html
{% extends "jobseekertemplates/jobseekerbase.html" %}
{% block job %}active{% endblock %}


{% block content %}
<h4>Job Lists</h4>
<div class="row">
	<div class="col-md-9">
		<diV class="row">
			{% for job in jobs %}
			<div class="col-md-4">
				<u><a href="{% url 'jobapp:jobdetail' job.id %}"><h2>{{job.title}}</h2></a></u>
				<img src="{{job.image.url}}" class="img-fluid">
			</div>
			<div class="clear-fix"></div>
			{% endfor %}
		</diV>
	</div>
	<div class="col-md-3">
		<div class="row">
			<h3>Latest jobs</h3>
			{% for job in jobs %}
			<div class="col-md-12">
				<u><a href="{% url 'jobapp:jobdetail' job.id %}"><h2>{{job.title}}</h2></a></u>
				<img src="{{job.image.url}}" class="img-fluid">
			</div>
			{% endfor %}
		</div>
		<div class="clear-fix"></div>
	</div>
		
</div>

{% endblock %}

templates/jobseekertemplates/joblogin.html
{% extends "jobseekertemplates/jobseekerbase.html" %}
{% load static %}


{% block content %}

{% if error %}
<li class="text-danger">{{error}}</li>
{% endif %}

<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button>Login</button>
</form>

<h4>register for new user</h4>
<a href="{% url 'jobapp:jobseekerregistration' %}">register as jobseeker</a>
or
<a href="{% url 'jobapp:employerregistration' %}">register as employer</a>


{% endblock %}

templates/jobseekertemplates/jobseekerbase.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>jobsnepal</title>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all" />


</head>
<body class="container">
  <br>
  <nav class="navbar navbar-expand-lg navbar-dark" style="height: 100px; background-color: #69D67B;">
  <a style="color: #800000" class="navbar-brand" href="/">kaamkaaz.com</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% block home %}{% endblock %}">
        <a class="nav-link" href="{% url 'jobapp:jobseekerhome' %}">Home <span class="sr-only">(current)</span></a> 
      </li>
      <li class="nav-item {% block job %}{% endblock %}">
        <a class="nav-link" href="{% url 'jobapp:joblist' %}">Jobs</a>
      </li>
      <li class="nav-item {% block events %}{% endblock %}">
        <a class="nav-link" href="">Events</a>
      </li>
      <li class="nav-item {% block blog %}{% endblock %}">
        <a class="nav-link" href="">Our Blogs</a>
      </li>
      <li class="nav-item {% block about %}{% endblock %}">
        <a class="nav-link" href="">About Us</a>
      </li>
      {% if request.user.is_authenticated and request.user.groups.first.name == "jobseeker" %}
      
        <p>Logged in as : {{request.user}}</p>
     <li class="nav-item">
      <a class="nav-link" href="{% url 'jobapp:jobseekerprofile' %}">My Pofile</a>
      </li>


      <li class="nav-item {% block logout %}{% endblock %}">
        <a class="nav-link" href="{% url 'jobapp:logout' %}">logout</a>
      </li>    
      {% else %}
      <li class="nav-item {% block registration %}{% endblock %}">
        <a class="nav-link" href="{% url 'jobapp:jobseekerregistration' %}">Register</a>
      </li>
      <li class="nav-item {% block login %}{% endblock %}">
        <a class="nav-link" href="{% url 'jobapp:joblogin' %}">login</a>
      </li>
      {% endif %}

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-info my-2 my-sm-0 " type="submit">Search</button>
    </form>
  </div>
</nav>
<br>




{% block content %}



{% endblock %}

<div class="footer">
  <h3 style="text-align: center;background-color: ">About Us</h3>
  <p>Kathmandu Jobs is Nepal's First Job Portal dedicated to IT Jobs.General/Marketing Contact: info@kathmandujobs.com Customer Support Hotline: +977-9801034779 (11 am - 4 pm)</p>
  <p style="text-align: center;">© All rights reserved with Kaamkaaz.com</p>
</div>

	<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.0.min.js"></script>

	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

	<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>

templates/jobseekertemplates/jobseekerhome.html
{% extends "jobseekertemplates/jobseekerbase.html" %}
{% block home %}active{% endblock %}

{% block content %}

<div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
  	{% for slider in sliders %}
    <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}" data-interval="10000">
      <img style="height: 250px;width:100%" src="{{slider.image.url}}" class="d-block" alt="...">
    </div>
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>




{% endblock %}

templates/jobseekertemplates/jobseekerjobapply.html
{% extends "jobseekertemplates/jobseekerbase.html" %}


{% block content %}
<h3>Job Application Form</h3>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<button>Apply</button>
</form>

{% endblock %}

templates/jobseekertemplates/jobseekerprofile.html
{% extends "jobseekertemplates/jobseekerbase.html" %}
{% load static %}
{% block content %}
<h3>My Profile</h3><hr>
<h4>Name:{{jobseeker.name}}</h4>

<h3>Job I have applied</h3>
<table class="table">
	<thead>
		<tr>
			<th>sn</th>
			<th>title</th>
			<th>company</th>
			<th>date</th>
		</tr>
	</thead>
	<tbody>
		{% for jobappl in jobseeker.jobapplication_set.all %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td>{{jobappl.job.title}}</td>
			<td>{{jobappl.job.employer.company}}</td>
			<td>{{jobappl.created_at}}</td>
		</tr>
		{% endfor %}
	</tbody>
	
</table>



{% endblock %}

templates/jobseekertemplates/jobseekerregistration.html
{% extends "jobseekertemplates/jobseekerbase.html" %}

{% block registration %}active{% endblock %}
{% block content %}

<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<button>register</button>
	
</form>

{% endblock %}